// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(admin)/dashboard.tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/users/[id].ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/users/[id].tsx";
import * as $7 from "./routes/users/_layout.tsx";
import * as $8 from "./routes/users/_middleware.ts";
import * as $9 from "./routes/users/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/(admin)/dashboard.tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/users/[id].ts": $4,
    "./routes/index.tsx": $5,
    "./routes/users/[id].tsx": $6,
    "./routes/users/_layout.tsx": $7,
    "./routes/users/_middleware.ts": $8,
    "./routes/users/index.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
